client_config_backend: settings
client_config:
  client_id: 960075369615-1e8l3q50grkiobra4p3oo66tp3ekt2u8.apps.googleusercontent.com
  client_secret: VXv6mvHXiS0o-uJvclMAVfkT
  revoke_uri: https://accounts.google.com/o/oauth2/revoke

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive